### ISSUE TITLE
Let's reconsider naming of CaseNode fields

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1816]
I propose to look at `CaseNode` and ensure that its field names are accurate and precise:

```yaml
  - name: CaseNode
    fields:
      - name: predicate
        type: node?
      - name: conditions
        type: node[]
      - name: consequent
        type: node?
        kind: ElseNode
# ...
```

TBH I find confusing `predicate`, `conditions` and `consequent` names:
- `predicate` - it isn't a predicate (something that returns true/false) - it's probably expression, object-to-match, target-to-match, value-to-compare etc
- `conditions` - it could be not only conditions, but value to compare with `predicate` (using `#===`); also it's more than just conditions - there is a __then__ branch - code to execute. So it could be branches, clauses...
- `consequent` - it might be a proper name actually but not sure that it's obvious for a reader what part of the case operator it matches. It could be more explicit - alternative-branch, default-branch, otherwise...

What do you think?
